/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst";
export {};
declare module "sst" {
    export interface Resource {
        DLQ: {
            type: "sst.aws.Queue";
            url: string;
        };
        MyTable: {
            name: string;
            type: "sst.aws.Dynamo";
        };
        MyWeb: {
            type: "sst.aws.Remix";
            url: string;
        };
        Queue: {
            type: "sst.aws.Queue";
            url: string;
        };
        SessionSecret: {
            type: "sst.sst.Secret";
            value: string;
        };
    }
}
